apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: apiserver
        image: us-docker.pkg.dev/minherz/examples/apiserver
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        env:
        - name: CONSULTING_SERVICE_URL
          value: http://consulting-svc:8080/
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: apiserver-svc
spec:
  type: LoadBalancer
  selector:
    app: apiserver
  ports:
  - name: http
    port: 80
    targetPort: 8080