apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulting
spec:
  selector:
    matchLabels:
      app: consulting
  template:
    metadata:
      labels:
        app: consulting
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: consulting
        image: us-docker.pkg.dev/minherz/examples/consulting
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: consulting-svc
spec:
  type: ClusterIP
  selector:
    app: consulting
  ports:
  - name: http
    port: 8080
    targetPort: 8080